// constants to allow index.js and generateMardown.js to communiate with each other
const inquirer = require('inquirer');
const fs = require('fs');
const generateMarkdown = require('./utils/generateMarkdown.js');
// array of questions that will be asked to generate the readme, the licenses are a list that the user can select
const questions = [
    {
        type: 'input',
        name: 'title',
        message: 'What is the title of your project?',
    },
    {
        type: 'input',
        name: 'description',
        message: 'How would you describe your project?',
    },
    {
        type: 'input',
        name: 'installation',
        message: 'What are the steps required to install your project?',
    },
    {
        type: 'input',
        name: 'usage',
        message: 'How do you use your application?',
    },
    {
        type: 'list',
        name: 'license',
        choices: [
            'None',
            'Apache License 2.0',
            'GNU General Public License v3.0',
            'MIT License',
            'BSD 2-Clause "Simplified" License',
            'BSD 3-Clause "New" or "Revised" License',
            'Boost Software License 1.0',
            'Creative Commons Zero v1.0 Universal',
            'Eclipse Public License 2.0',
            'GNU Affero General Public License v3.0',
            'GNU General Public License v2.0',
            'GNU Lesser General Public License v2.1',
            'Mozilla Public License 2.0',
            'The Unlicense',
        ],
        message: 'What license was used for this project?',
    },
    {
        type: 'input',
        name: 'contributing',
        message: 'How can someone contribute to your project?',
    },
    {
        type: 'input',
        name: 'tests',
        message: 'How do you run tests for your application?',
    },
    {
        type: 'input',
        name: 'githubUsername',
        message: 'What is your GitHub username?',
    },
    {
        type: 'input',
        name: 'email',
        message: 'What is your email address?',
    },
];
// function to create the readme after collecting data from generateMarkdown function
// the inquirer prompts the questions from above, then the answers get used in the generateMarkdown function
// if the function returns a blank, the readme is not generated and the user is notified
// otherwise the readme is created with the writefile function using the content generated by the generateMarkdown function
// if there is an error, it is reported in the console, otherwise the user is notified that the file is created
function writeToFile(fileName, data) {
    inquirer
        .prompt(questions)
        .then((answers) => {
            const readmeContent = generateMarkdown(answers);
            if (readmeContent === '') {
                console.log('README.md not created. Please try again.')
            } else {
                fs.writeFile('README.md', readmeContent, (err) =>
                    err ? console.log(err) : console.log('Successfully created README.md')
                )
            };
        })
};
// this function runs when the file is called. it lets the user know what is required.
function init() {
    console.log('Title, Description, Usage and either a Github username or an email is required.')
    writeToFile();
};
// executes init function
init();
